[real_ip]

# Number of values to trust for X-Forwarded-For.
# Cloud Run uses load balancers, so we need to trust forwarded headers
x_for = 1

# The prefix defines the number of leading bits in an address that are compared
# to determine whether or not an address is part of a (client) network.
ipv4_prefix = 32
ipv6_prefix = 48

[botdetection.ip_limit]

# To get unlimited access in a local network, by default link-local addresses
# (networks) are not monitored by the ip_limit
filter_link_local = false

# DISABLE link_token method for API access - this is what was blocking requests
link_token = false

[botdetection.ip_lists]

# In the limiter, the ip_lists method has priority over all other methods -> if
# an IP is in the pass_ip list, it has unrestricted access and it is also not
# checked if e.g. the "user agent" suggests a bot (e.g. curl).

block_ip = [
  # Add IPs to block here if needed
]

pass_ip = [
  # Add trusted IPs here if you want to whitelist specific clients
  # '192.168.0.0/16',      # IPv4 private network example
]

# Disable automatic passlist of SearXNG organization IPs for public API
pass_searxng_org = false

[botdetection.http_accept]
# Disable HTTP Accept header validation that blocks API clients
suspicious_http_accept = false

[botdetection.http_accept_encoding]
# Disable Accept-Encoding header validation
suspicious_http_accept_encoding = false

[botdetection.http_accept_language]
# Disable Accept-Language header validation
suspicious_http_accept_language = false

[botdetection.http_user_agent]
# Disable User-Agent validation that blocks programmatic access
suspicious_http_user_agent = false
