# SPDX-License-Identifier: AGPL-3.0-or-later
# SearXNG settings optimized for Google Cloud Run deployment

use_default_settings: true

general:
  debug: false
  instance_name: "SearXNG Cloud API"
  enable_metrics: false
  donation_url: false
  contact_url: false
  privacypolicy_url: false

brand:
  new_issue_url: false
  docs_url: false
  public_instances: false
  wiki_url: false

search:
  safe_search: 0
  autocomplete: ""
  autocomplete_min: 4
  default_lang: "en"
  ban_time_on_fail: 5
  max_ban_time_on_fail: 120
  suspended_times:
    SearxEngineAccessDenied: 86400
    SearxEngineCaptcha: 86400
    SearxEngineTooManyRequests: 3600
    cf_SearxEngineCaptcha: 86400
    cf_SearxEngineAccessDenied: 86400
    recaptcha_SearxEngineCaptcha: 86400
  formats:
    - html
    - json
    - csv
    - rss

server:
  # Cloud Run configuration
  port: 8080
  bind_address: "0.0.0.0"
  public_instance: true
  image_proxy: true
  
  # Security - override with environment variable in production
  secret_key: "ultrasecretkey"  # MUST be overridden via SEARXNG_SECRET_KEY env var
  
  # CORS headers for API access
  default_http_headers:
    X-Content-Type-Options: nosniff
    X-Download-Options: noopen
    X-Robots-Tag: noindex, nofollow
    Referrer-Policy: no-referrer
    Access-Control-Allow-Origin: "*"
    Access-Control-Allow-Methods: "GET, POST, OPTIONS"
    Access-Control-Allow-Headers: "Content-Type, Authorization"
    Access-Control-Max-Age: "86400"

ui:
  static_use_hash: true
  default_locale: "en"
  query_in_title: false
  infinite_scroll: false
  center_alignment: false
  cache_url: https://web.archive.org/web/
  default_theme: simple
  theme_args:
    simple_style: auto

# Disable features not needed for API usage
preferences:
  lock:
    - autocomplete
    - method
    - safesearch

# Minimal engine configuration for faster startup
engines:
  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
    categories: [general, web]
    disabled: false
    
  - name: google
    engine: google
    shortcut: go
    categories: [general, web]
    disabled: false
    use_mobile_ui: false
    
  - name: bing
    engine: bing
    shortcut: bi
    categories: [general, web]
    disabled: false
    
  - name: wikipedia
    engine: wikipedia
    shortcut: wp
    categories: [general]
    disabled: false
    
  - name: github
    engine: github
    shortcut: gh
    categories: [it]
    disabled: false

# Disable plugins that might cause issues in Cloud Run
enabled_plugins: []

# Disable checker for faster startup
checker:
  off_when_debug: true
